### ISSUE TITLE
1.0.0 doesn't work in 1.10.2

### ISSUE THREAD

**Issue by bochen415** [Team-AbCiv/RobustIMC#1]
As title
It's asking for mc 1.11

**Comment by 3TUSK** [comment]
Heck, apparently I forget to remove the version restriction... which should be for testing purpose and still exists for no reason. You can expect to have a fixed build in next 24 hours.  
Sorry for replying late - I was busy these days.

Also a question: how did you find this mod?

**Comment by 3TUSK** [comment]
https://github.com/Team-AbCiv/RobustIMC/releases/tag/1.0.1

**Comment by bochen415** [comment]
Thanks, I found it in a comment in the Issues section of one of the mods, don't remember which one tho, it was about missing Redstone Furnace recipes for MFR items in 1.10.2.
